apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: agent-efs-sc #efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-056bf146402dcfca8::fsap-0c3452c79cf2d8eee