apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "kiali-server.fullname" . }}
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  hosts:
  - {{ .Values.gateway.hosts }}
  gateways:
  - {{ template "kiali-server.fullname" . }}-gateway
  http:
  - match:
  {{- range .Values.virtualservice.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
  {{- end }}
    route:
    - destination:
        host: {{ template "kiali-server.fullname" . }}
        port:
          number: {{ .Values.virtualservice.port }}
    headers:
      {{- toYaml .Values.virtualservice.header | nindent 8 }}
